logging:
  level:
    tech:
      jhipster:
        sampleapp: INFO
spring:
  application:
    name: Sampleapp
  threads:
    virtual:
      enabled: true
  task:
    execution:
      pool:
        keep-alive: 10s
        max-size: 16
        queue-capacity: 100
      thread-name-prefix: sampleapp-task-
    scheduling:
      pool:
        size: 2
      thread-name-prefix: sampleapp-scheduling-
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/sampleapp
    username: sampleapp
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        jdbc:
          batch_size: 25
          time_zone: UTC
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
  liquibase:
    change-log: classpath:config/liquibase/master.xml
server:
  port: 8081
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
  info:
    env:
      enabled: true
    # Git Information
    git:
      enabled: true
      mode: full
