logging:
  level:
    tech:
      jhipster:
        sampleapp: INFO
spring:
  application:
    name: Sampleapp
  threads:
    virtual:
      enabled: true
  task:
    execution:
      pool:
        keep-alive: 10s
        max-size: 16
        queue-capacity: 100
      thread-name-prefix: sampleapp-task-
    scheduling:
      pool:
        size: 2
      thread-name-prefix: sampleapp-scheduling-
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
server:
  port: 8081
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
