logging:
  level:
    tech:
      jhipster:
        sampleapp: INFO
spring:
  application:
    name: Sampleapp
  threads:
    virtual:
      enabled: true
server:
  port: 8081
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
